[tool.ruff]
select = ["ALL"]
ignore = []
line-length = 150
exclude = [
    "migrations",
    "manage.py",
    "__pycache__",
]

[tool.ruff.lint]
ignore = ["S101", "TRY003", "EM101", "PT009", "PT027", "S106"]
