# Generated by Django 5.0.3 on 2024-04-02 22:44

import reminder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0002_alter_reminder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="end_date_time",
            field=models.DateTimeField(
                validators=[reminder.models.validate_future_datetime]
            ),
        ),
    ]
