"""Reminder App config class."""
from django.apps import AppConfig


class ReminderConfig(AppConfig):
    """Reminder App config class. AutoGenerated."""

    default_auto_field = "django.db.models.BigAutoField"
    name = "reminder"
